spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mynewdb
    username: postgres
    password: MiRoSlAv
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

